name: 'Marlin_firmware_config_tool'
description: 'Use it to set your own custome Configuration.h/Configuration_adv.h file.'
inputs:
  BOARD:
    description: 'input the board name'
    required: true
    default: 'BOARD_CCROBOT_MEEB_3DP'
outputs:
  RESULT: #
    description: 'output result string'
runs:
  using: 'node12'
  main: 'action.js'
branding:
  icon: 'terminal'
  color: 'green'


