name: 'make image tool'
description: 'Use it to join the marlin firmware and bootloader images.'
inputs:
  BOOTLOADER_PATH:
    description: 'input the path of bootloader image.'
    required: true
    default: 'xxx'
  BOOTLOADER_OFFSET:
    description: 'input the offset value of bootloader image.'
    required: true
    default: '0x0'
  MARLIN_PATH:
    description: 'input the path of marlin image.'
    required: true
    default: 'xxx'
  MARLIN_OFFSET:
    description: 'input the offset value of marlin image.'
    required: true
    default: '0x2000'  
  FILE_OUTPUT_NAME:
    description: 'input the file path of the final image file.'
    required: true
    default: 'xxx'      
outputs:
  RESULT: #
    description: 'output result string'
runs:
  using: 'node12'
  main: 'action.js'
branding:
  icon: 'terminal'
  color: 'green'


