#===================================================================================
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: CI

on: [push]

env:
  BOOTLOADER_PATH: 'bootloader/bootloader_meeb_3dp.bin'
  BOOTLOADER_OFFSET: '0x0'
  MARLIN_PATH: 'Marlin_v2/firmware.bin'
  MARLIN_OFFSET: '0x2000'
  FILE_OUTPUT_NAME: 'Marlin_v2/firmware_with_bootloader.bin'
  
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
  
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2
      with:
        ref: master    
    
    - name: Do real test
      id: testbench
      uses: ccccmagicboy/make_image@master
      with:
        BOOTLOADER_PATH: $BOOTLOADER_PATH
        BOOTLOADER_OFFSET: $BOOTLOADER_OFFSET
        MARLIN_PATH: $MARLIN_PATH
        MARLIN_OFFSET: $MARLIN_OFFSET
        FILE_OUTPUT_NAME: $FILE_OUTPUT_NAME
        
    - name: Print the result
      run: |
        echo ${{ steps.testbench.outputs.RESULT }}
      shell: bash
        
        
        